openapi: 3.0.0
info:
  title: Booking API
  version: 1.0.0
  description: API for managing bookings

paths:
  /api/booking:
    post:
      summary: Creates a new booking
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Booking'
      responses:
        '200':
          description: Booking created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
    get:
      summary: Fetches all bookings
      responses:
        '200':
          description: List of all bookings
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Booking'

  /api/booking/{id}:
    get:
      summary: Fetches a booking by its ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Booking fetched successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
    put:
      summary: Updates an existing booking
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Booking'
      responses:
        '200':
          description: Booking updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
    delete:
      summary: Deletes a booking by its ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Booking deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteResponse'

components:
  schemas:
    Booking:
      type: object
      properties:
        bookingId:
          type: integer
        hotelId:
          type: integer
        userId:
          type: integer
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
    DeleteResponse:
      type: object
      properties:
        message:
          type: string